# Generated by Django 4.2 on 2023-06-03 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArea', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=15)),
                ('tipoContrato', models.CharField(max_length=15)),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCentro', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('rut', models.CharField(max_length=15)),
                ('fechaInicioAtencion', models.DateField()),
                ('vigente', models.BooleanField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15)),
                ('idArea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.area')),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cargo')),
                ('idCentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centro')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRegion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreZona', models.CharField(max_length=70)),
                ('idRegion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoTurno', models.CharField(max_length=10)),
                ('fechaInicio', models.DateField()),
                ('horaInicio', models.TimeField()),
                ('fechaTermino', models.DateField()),
                ('horaTermino', models.TimeField()),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
                ('idProfesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sueldoBase', models.IntegerField()),
                ('gratificacion', models.IntegerField()),
                ('horaExtra', models.IntegerField()),
                ('bonos', models.IntegerField()),
                ('aguinaldo', models.IntegerField()),
                ('vacaciones', models.IntegerField()),
                ('viatico', models.IntegerField()),
                ('asignacionFamiliar', models.IntegerField()),
                ('colacion', models.IntegerField()),
                ('movilizacion', models.IntegerField()),
                ('salaCuna', models.IntegerField()),
                ('totalHaberes', models.IntegerField()),
                ('totalImponible', models.IntegerField()),
                ('afp', models.IntegerField()),
                ('isapre', models.IntegerField()),
                ('fonasa', models.IntegerField()),
                ('segCes', models.IntegerField()),
                ('imptoUnico', models.IntegerField()),
                ('ctaAfp', models.IntegerField()),
                ('anticipos', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('ley3', models.IntegerField()),
                ('totalDescuento', models.IntegerField()),
                ('liquido', models.IntegerField()),
                ('fechaPago', models.DateField()),
                ('idProfesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesional')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='idRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('idCargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsistencia', models.DateField()),
                ('asisteProfesional', models.BooleanField()),
                ('estado', models.IntegerField()),
                ('idProfesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAlerta', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('idAsistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistencia')),
                ('idPaciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
