# Generated by Django 4.2.2 on 2023-07-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
